# Lain-Dotfiles
# Alacritty config

# Font settings
[font]
normal={family="JetBrainsMono Nerd Font Mono", style="regular"}
size=11
# Window settings
[window]
opacity=0.85
# Color Settings
[colors]
[colors.primary]
foreground="#d27389" 
background="#000000"
[colors.normal]
red="#90201f"
white="#eda2a9"
blue="#87ceeb"
magenta="#d27389"

green="#7AFF96"
yellow="#ECFF85"
# Bindings
[keyboard]
bindings=[

    {key="-", mods="Alt", action="DecreaseFontSize"},
    {key="=", mods="Alt", action="IncreaseFontSize"}

]













