# Yukino-dotfiles
# Kitty config

# fonts settings
font_family JetBrainsMono Nerd Font Propo
font_size 13

# window
background_opacity 0.9

# colors
foreground #c8ccd4
background #111112
color0 #1d212f
color1 #640b11
color2 #006400
color3 #fdfd96
color4 #6c88d4
color5
color6
color7 #c8ccd4

# keybinds
