# Rei Dotfiles
# Polybar Config
#         {HARDWARE} 				    		{SOFTWARE}
#[{i3}] [{storage}] [{ram}{cpu}{battery}] [{text}] [{cmus}] [{wpm}{volume}{wifi}{time}]

[global]
interval=2

[colors]
white="#fdfdfd"
gray="#c6c2c7"
black="#382c3a"
transparentBlack="#aa000000"
red="#90201f"
blue="#87ceeb"
yellow="#ffff00"
magenta="#d27389"

format-blue=#87ceeb
format-red=%{F#90201f}

text=${self.white}
textAlt=${self.gray}
textUrgent=${self.red}
border=${self.gray}
background=${self.black}

[bar/mainbar]
override-redirect=true
height=30
width=1900
offset-y=5
offset-x=10
background=${colors.background}
foreground=${colors.text}
radius=8.0
border-size=2
border-color=${colors.border}
separator=" | "
font-0=JetBrainsMono Nerd Font Propo:size=12;2
monitor=${env:MONITOR:}

wm-restack=i3

modules-left = i3
modules-center = text
modules-right = pulseaudio wifi date

[settings]
pseudo-transparency=true

[module/text]
type = custom/text
format = <label>
label = will things get better?

[module/i3]
type=internal/i3
enable-scroll=false
enable-click = false

format=[  <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.background}

label-focused = (%index%)
label-focused-foreground=${colors.textAlt}
label-focused-background = ${colors.background}
label-focused-padding = 1

label-unfocused = [%index%]
label-unfocused-padding = 1

[module/filesystem]
type=internal/fs
interval=${global.interval}
mount-0=/
spacing=1

format-unmounted=<label-unmounted>
format-mounted=<label-mounted>

label-unmounted=%mountpoint%:
label-mounted=%mountpoint%: %percentage_used%% of %total%

[module/memory]
type=internal/memory
interval=${global.interval}
format=": %{F#87ceeb}<label>"
label=%gb_used%
[module/cpu]
type=internal/cpu
interval=${global.interval}
format=": %{F#87ceeb}<label>"
label=%percentage%%
[module/battery]
type=internal/battery
poll-interval=${global.interval}
full-at=99
low-at=10

battery=BAT0
adapter=AC

format-charging=󰁹: <animation-charging> %{F#87ceeb}<label-charging>
format-discharging=󰁹: <animation-discharging> %{F#87ceeb}<label-discharging>
format-full=󰁹:   %{F#87ceeb}<label-full>
format-low=󰁹: %{F#90201f}<animation-low> %{F#87ceeb}<label-low>

label-charging=%percentage%%
label-discharging=%percentage%%
label-full=%percentage%%
label-low=%percentage%%

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/player-cmus]
type = custom/script
exec = ~/.config/polybar/player-cmus.sh
tail = true

[module/info-hackspeed]
type=custom/script
exec=~/.config/polybar/info-hackspeed.sh
tail=true
[module/pulseaudio]
type=internal/pulseaudio
interval=${global.interval}
format-volume=: <label-volume>
format-muted=
[module/wifi]
type=internal/network
interval=${global.interval}
interface=wlan0
format-connected=<label-connected>
format-disconnected=<label-disconnected>
label-connected=󰖩
label-disconnected=󰖪
[module/date]
type=internal/date
interval=${global.interval}
time=%I:%M
format=󱑓 : <label>  ]
label=%time%










