# Rei-Dotfiles
# Polybar Config

[colors]
black="000000"
red="90201f"
gray="525252"
blue="87ceeb"
yellow="dadf27"
magenta="d27389"
white="ffebec"

barBorder=${self.red}
barBackground=${self.black}
textNormal=${self.white}
textUrgent=${self.red}

# Cmus Module
[module/player-cmus]
type = custom/script
exec = ~/.config/polybar/player-cmus.sh
tail = true

# Audio Module
[module/pulseaudio]
type=internal/pulseaudio
interval=2.0

format-volume=[=<label-volume>]
format-muted=[]

[module/info-hackspeed]
type=custom/script
exec=~/.config/polybar/info-hackspeed.sh
tail=true

# Filesystem Module
[module/filesystem]
type=internal/fs
interval=2.0
mount-0=/
mount-1=/mnt/drive
spacing=1

format-unmounted=<label-unmounted>
format-mounted=<label-mounted>

label-mounted=[%mountpoint%:%percentage_used%% of %total%]
label-unmounted=[%mountpoint%:]

# CPU Module
[module/cpu]
type=internal/cpu
interval=2.0

format=[=<label>]

label=%percentage%%

# RAM Module
[module/memory]
type=internal/memory
inteval=2.0

format=[=<label>]

label=%gb_used%

# i3 Workspace Module
[module/i3]
type=internal/i3
enable-click=false

format = <label-state> <label-mode>

label-unfocused-foreground = ${colors.textNormal}

label-focused-foreground = ${colors.blue}
label-focused-background = ${colors.barBackground}
label-focused-padding = 1

label-focused = {%index%}
label-unfocused = [%index%]
label-unfocused-padding = 1

# Middle text
[module/text]
type=custom/text

format=<label>
format-foreground=${colors.blue}

label=[Rei Ayanami]

# Wifi module
[module/wireless-network]
type=internal/network
interface=wlan0

interval=2.0

format-connected=<label-connected>
format-disconnected=<label-disconnected>

label-connected=[󰖩]
labal-disconnected=[󰖪]

# Time Module
[module/date]
type=internal/date
interval=2.0
time=%I:%M

format=[󱑓=<label>]
format-foreground=${colors.textNormal}

label=%time%

# cmus bar
[bar/cmusbar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.black}
foreground=${colors.textNormal}

modules-center= player-cmus

override-redirect=true
wm-restack=i3

width=270
height=24pt
offset-y=5
offset-x= 1130

radius = 8

border-size=2
border-color=${colors.red}

# storage bar
[bar/storagebar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.black}
foreground=${colors.textNormal}

modules-center= filesystem

override-redirect=true
wm-restack=i3

width=410
height=24pt
offset-y=5
offset-x= 165

radius = 8

border-size=2
border-color=${colors.red}

# info bar
[bar/infobar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.black}
foreground=${colors.textNormal}

modules-center= info-hackspeed pulseaudio wireless-network memory cpu  

override-redirect=true
wm-restack=i3

width=400
height=24pt
offset-y=5
offset-x= 1410

radius = 8

border-size=2
border-color=${colors.red}

# text bar
[bar/textbar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.barBackground}
foreground=${colors.textNormal}

modules-center= text  

override-redirect=true
wm-restack=i3

width=195
height=24pt
offset-y=5
offset-x= 850

radius = 8

border-size=2
border-color=${colors.barBorder}

# time bar 
[bar/timebar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.black}
foreground=${colors.textNormal}

modules-right= date 

override-redirect=true
wm-restack=i3

width=90
height=24pt
offset-y=5
offset-x=1820

radius = 8

border-size=2
border-color=${colors.red}

# i3 bar
[bar/i3bar]
separator="|"
padding=0

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.barBackground}
foreground=${colors.textNormal}

modules-left= i3 

override-redirect=true
wm-restack=i3

width=140
height=24pt
offset-y=5
offset-x=10

radius = 8

border-size=2
border-color=${colors.barBorder}










