#rei-dotfiles picom configuration

# rendering backend (default)
backend = "glx"

# Opacity
frame-opacity = 0.9;

# Corner rounding
corner-radius = 1;

# blurring
blur-method = "dual_kawase";
blur-size = 3;
blur-strength = 3;

