# Lain-Dotfiles
# Polybar Config

[colors]
black="000000"
red="b22222"
gray="a7a7a7"
yellow="dadf27"
magenta="d27389"
lightMagenta="eda2a9"

textNormal=${self.magenta}
textSecondary=${self.lightMagenta}
textUrgent=${self.red}

# Audio Module
[module/pulseaudio]
type=internal/pulseaudio
interval=2.0

format-volume=[=<label-volume>]
format-muted=[]

# Filesystem Module
[module/filesystem]
type=internal/fs
interval=2.0
mount-0=/
mount-1=/mnt/drive
spacing=1

format-unmounted=<label-unmounted>
format-mounted=<label-mounted>

label-mounted=[%mountpoint%:%percentage_used%% of %total%]
label-unmounted=[%mountpoint%:]

# CPU Module
[module/cpu]
type=internal/cpu
interval=2.0

format=[=<label>]

label=%percentage%%

# RAM Module
[module/memory]
type=internal/memory
inteval=2.0

format=[=<label>]

label=%gb_used%

# i3 Workspace Module
[module/i3]
type=internal/i3
enable-click=false

format = <label-state> <label-mode>

label-focused = <%index%>
label-focused-foreground = ${colors.black}
label-focused-background = ${colors.magenta}
label-focused-padding = 1

label-unfocused = [%index%]
label-unfocused-padding = 1

# Middle text
[module/lainText]
type=custom/text

format=<label>
format-foreground=${colors.textSecondary}

label=[Let's All Love Lain]

# Wifi module
[module/wireless-network]
type=internal/network
interface=wlan0

interval=2.0

format-connected=<label-connected>
format-disconnected=<label-disconnected>

label-connected=[󰖩]
labal-disconnected=[󰖪]

# Time Module
[module/date]
type=internal/date
interval=2.0
time=%I:%M

format=[󱑓=<label>]
format-foreground=${colors.textNormal}

label=%time%

# Overral bar options
[bar/mainbar]
separator="|"
padding=2

font-0=JetBrainsMono Nerd Font Propo:size=11;2

background=${colors.black}
foreground=${colors.textNormal}

modules-left= i3 filesystem
modules-center= lainText
modules-right= memory cpu pulseaudio wireless-network date

override-redirect=true
wm-restack=i3

width=1900
height=24pt
offset-y=5
offset-x=10

border-size=2
border-color=${colors.textNormal}










