# Lain-Dotfiles
# Polybar Config

[colors]
black="000000"
red="b22222"
gray="a7a7a7"
yellow="dadf27"
magenta="d27389"
lightMagenta="eda2a9"

textNormal=${self.magenta}
textSecondary=${self.lightMagenta}
textUrgent=${self.red}

# Audio Module
[module/pulseaudio]
type=internal/pulseaudio
interval=2.0

format-volume=[audio-<label-volume>]
format-muted=[audio-muted]

# Filesystem Module
[module/filesystem]
type=internal/fs
interval=2.0
mount-0=/
mount-1=/mnt/drive
spacing=1

format-unmounted=<label-unmounted>
format-mounted=<label-mounted>

label-mounted=[%mountpoint%:%percentage_used%% of %total%]
label-unmounted=[%mountpoint%:]

# CPU Module
[module/cpu]
type=internal/cpu
interval=2.0

format=[=<label>]

label=%percentage%%

# RAM Module
[module/memory]
type=internal/memory
inteval=2.0

format=[=<label>]

label=%gb_used%

# i3 Workspace Module
[module/i3]
type=internal/i3
enable-click=false

format = <label-state> <label-mode>

label-focused = [%index%]
label-focused-foreground = ${colors.black}
label-focused-background = ${colors.magenta}
label-focused-padding = 1

label-unfocused = [%index%]
label-unfocused-padding = 1

# Middle text
[module/text]
type=custom/text

format=<label>
format-foreground=${colors.textSecondary}

label=[i <3 gothangelz]

# Wifi module
[module/wireless-network]
type=internal/network
interface=wlp0s20f3

interval=2.0

format-connected=<label-connected>
format-disconnected=<label-disconnected>

label-connected=[wifi-connected]
labal-disconnected=[no-wifi]

# Cmus Module
[module/cmus]
type=custom/script
exec=~/.config/polybar/player-cmus.sh
tail=true

# Battery Module
[module/battery]
type = internal/battery
full-at = 100
low-at = 10
battery = BAT1
adapter = ACAD
poll-interval = 2
format-charging = [<animation-charging><label-charging>]
format-discharging = [<animation-discharging><label-discharging>]
label-charging = %percentage%%
label-discharging = %percentage%%

label-full = [fully charged]
label-low = [low battery - %percentage%%]

animation-charging-0 = +
animation-charging-1 = 
animation-charging-2 = +
animation-charging-3 = 
animation-charging-4 = +
animation-charging-framerate = 500

animation-discharging-0 = -
animation-discharging-1 = 
animation-discharging-2 = -
animation-discharging-3 = 
animation-discharging-4 = -
animation-discharging-framerate = 500

# Time Module
[module/date]
type=internal/date
interval=2.0
time=%I:%M

format=[<label>]
format-foreground=${colors.textNormal}

label=%time%

# Overral bar options
[bar/mainbar]
separator=" "
padding=2

font-0=White Rabbit:size=13;2

background=${colors.black}
foreground=${colors.textNormal}

modules-left= i3 cmus
modules-center= text
modules-right= battery pulseaudio wireless-network date

override-redirect=true
wm-restack=i3

width=1900
height=30pt
offset-y=5
offset-x=10

border-size=2
border-color=${colors.textNormal}









